language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

script:
  - "py.test dirvish_prometheus_metrics.py tests/"
